=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Nutanix
  # Network rule
  class NetworkRule
    # Select a protocol to allow.  Multiple protocols can be allowed by repeating network_rule object.  If a protocol is not configured in the network_rule object then it is allowed.
    attr_accessor :protocol

    # Description for network security rule that is for inbound or outbound
    attr_accessor :description

    attr_accessor :ip_subnet

    # List of TCP ports that are allowed by this rule.
    attr_accessor :tcp_port_range_list

    # List of UDP ports that are allowed by this rule.
    attr_accessor :udp_port_range_list

    # The set of categories that matching VMs need to have.
    attr_accessor :peer_specification_type

    attr_accessor :filter

    # List of service groups associated with this rule. The exiting fields for protocol or ports is not recommended for use and will be deprecated for these new fields at the API level.
    attr_accessor :service_group_list

    # List of ICMP types and codes allowed by this rule.
    attr_accessor :icmp_type_code_list

    attr_accessor :network_function_chain_reference

    # Timestamp of expiration time.
    attr_accessor :expiration_time

    # Unique identifier for inbound or outbound rule. This is system generated and used internally. User should not set this field while creating a new rule or should not modify it while updating the existing rule.
    attr_accessor :rule_id

    # List of address groups that are allowed access by this rule
    attr_accessor :address_group_inclusion_list

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'protocol' => :'protocol',
        :'description' => :'description',
        :'ip_subnet' => :'ip_subnet',
        :'tcp_port_range_list' => :'tcp_port_range_list',
        :'udp_port_range_list' => :'udp_port_range_list',
        :'peer_specification_type' => :'peer_specification_type',
        :'filter' => :'filter',
        :'service_group_list' => :'service_group_list',
        :'icmp_type_code_list' => :'icmp_type_code_list',
        :'network_function_chain_reference' => :'network_function_chain_reference',
        :'expiration_time' => :'expiration_time',
        :'rule_id' => :'rule_id',
        :'address_group_inclusion_list' => :'address_group_inclusion_list'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'protocol' => :'String',
        :'description' => :'String',
        :'ip_subnet' => :'IpSubnet',
        :'tcp_port_range_list' => :'Array<PortRange>',
        :'udp_port_range_list' => :'Array<PortRange>',
        :'peer_specification_type' => :'String',
        :'filter' => :'CategoryFilter',
        :'service_group_list' => :'Array<ServiceGroupReference>',
        :'icmp_type_code_list' => :'Array<NetworkRuleIcmpTypeCodeListInner>',
        :'network_function_chain_reference' => :'NetworkFunctionChainReference',
        :'expiration_time' => :'String',
        :'rule_id' => :'Integer',
        :'address_group_inclusion_list' => :'Array<AddressGroupReference>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Nutanix::NetworkRule` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Nutanix::NetworkRule`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'protocol')
        self.protocol = attributes[:'protocol']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'ip_subnet')
        self.ip_subnet = attributes[:'ip_subnet']
      end

      if attributes.key?(:'tcp_port_range_list')
        if (value = attributes[:'tcp_port_range_list']).is_a?(Array)
          self.tcp_port_range_list = value
        end
      end

      if attributes.key?(:'udp_port_range_list')
        if (value = attributes[:'udp_port_range_list']).is_a?(Array)
          self.udp_port_range_list = value
        end
      end

      if attributes.key?(:'peer_specification_type')
        self.peer_specification_type = attributes[:'peer_specification_type']
      end

      if attributes.key?(:'filter')
        self.filter = attributes[:'filter']
      end

      if attributes.key?(:'service_group_list')
        if (value = attributes[:'service_group_list']).is_a?(Array)
          self.service_group_list = value
        end
      end

      if attributes.key?(:'icmp_type_code_list')
        if (value = attributes[:'icmp_type_code_list']).is_a?(Array)
          self.icmp_type_code_list = value
        end
      end

      if attributes.key?(:'network_function_chain_reference')
        self.network_function_chain_reference = attributes[:'network_function_chain_reference']
      end

      if attributes.key?(:'expiration_time')
        self.expiration_time = attributes[:'expiration_time']
      end

      if attributes.key?(:'rule_id')
        self.rule_id = attributes[:'rule_id']
      end

      if attributes.key?(:'address_group_inclusion_list')
        if (value = attributes[:'address_group_inclusion_list']).is_a?(Array)
          self.address_group_inclusion_list = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@description.nil? && @description.to_s.length > 64
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 64.')
      end

      if !@expiration_time.nil? && @expiration_time.to_s.length > 64
        invalid_properties.push('invalid value for "expiration_time", the character length must be smaller than or equal to 64.')
      end

      if !@rule_id.nil? && @rule_id > 4095
        invalid_properties.push('invalid value for "rule_id", must be smaller than or equal to 4095.')
      end

      if !@rule_id.nil? && @rule_id < 0
        invalid_properties.push('invalid value for "rule_id", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@description.nil? && @description.to_s.length > 64
      return false if !@expiration_time.nil? && @expiration_time.to_s.length > 64
      return false if !@rule_id.nil? && @rule_id > 4095
      return false if !@rule_id.nil? && @rule_id < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      if description.to_s.length > 64
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 64.'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration_time Value to be assigned
    def expiration_time=(expiration_time)
      if expiration_time.nil?
        fail ArgumentError, 'expiration_time cannot be nil'
      end

      if expiration_time.to_s.length > 64
        fail ArgumentError, 'invalid value for "expiration_time", the character length must be smaller than or equal to 64.'
      end

      @expiration_time = expiration_time
    end

    # Custom attribute writer method with validation
    # @param [Object] rule_id Value to be assigned
    def rule_id=(rule_id)
      if rule_id.nil?
        fail ArgumentError, 'rule_id cannot be nil'
      end

      if rule_id > 4095
        fail ArgumentError, 'invalid value for "rule_id", must be smaller than or equal to 4095.'
      end

      if rule_id < 0
        fail ArgumentError, 'invalid value for "rule_id", must be greater than or equal to 0.'
      end

      @rule_id = rule_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          protocol == o.protocol &&
          description == o.description &&
          ip_subnet == o.ip_subnet &&
          tcp_port_range_list == o.tcp_port_range_list &&
          udp_port_range_list == o.udp_port_range_list &&
          peer_specification_type == o.peer_specification_type &&
          filter == o.filter &&
          service_group_list == o.service_group_list &&
          icmp_type_code_list == o.icmp_type_code_list &&
          network_function_chain_reference == o.network_function_chain_reference &&
          expiration_time == o.expiration_time &&
          rule_id == o.rule_id &&
          address_group_inclusion_list == o.address_group_inclusion_list
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [protocol, description, ip_subnet, tcp_port_range_list, udp_port_range_list, peer_specification_type, filter, service_group_list, icmp_type_code_list, network_function_chain_reference, expiration_time, rule_id, address_group_inclusion_list].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Nutanix.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
