=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Nutanix
  # Task details.
  class Task
    # Current state of the task.
    attr_accessor :status

    # UTC date and time in RFC-3339 format when task was last updated. 
    attr_accessor :last_update_time

    # In case of task failure this field will provide the error description. 
    attr_accessor :error_detail

    # Number of times the task has been updated. The value increases sequentially with each update of the task and can be used to verify if there have been changes to the task. 
    attr_accessor :logical_timestamp

    # Final expected state of the task. It is set when the task is aborted. 
    attr_accessor :requested_status

    attr_accessor :entity_reference_list

    # UTC date and time in RFC-3339 format when Task execution started. 
    attr_accessor :start_time

    # UTC date and time in RFC-3339 format when task was created. 
    attr_accessor :creation_time

    # UUID of the task.
    attr_accessor :uuid

    # Time in microseconds from epoch when the task execution started. 
    attr_accessor :start_time_usecs

    attr_accessor :cluster_reference

    # Reference to the sub-tasks.
    attr_accessor :subtask_reference_list

    # UTC date and time in RFC-3339 format when Task execution completed. 
    attr_accessor :completion_time

    # Time in microseconds from epoch when task was created. 
    attr_accessor :creation_time_usecs

    # Description of what currently the task is doing.
    attr_accessor :progress_message

    # Type of the operation tracked by the task.
    attr_accessor :operation_type

    # Time in microseconds from epoch when task execution completed. 
    attr_accessor :completion_time_usecs

    # In case of task failure this field will provide the error code. 
    attr_accessor :error_code

    # The completion percentage for the task.
    attr_accessor :percentage_complete

    # API Version of the Nutanix v3 API framework.
    attr_accessor :api_version

    attr_accessor :parent_task_reference

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'status' => :'status',
        :'last_update_time' => :'last_update_time',
        :'error_detail' => :'error_detail',
        :'logical_timestamp' => :'logical_timestamp',
        :'requested_status' => :'requested_status',
        :'entity_reference_list' => :'entity_reference_list',
        :'start_time' => :'start_time',
        :'creation_time' => :'creation_time',
        :'uuid' => :'uuid',
        :'start_time_usecs' => :'start_time_usecs',
        :'cluster_reference' => :'cluster_reference',
        :'subtask_reference_list' => :'subtask_reference_list',
        :'completion_time' => :'completion_time',
        :'creation_time_usecs' => :'creation_time_usecs',
        :'progress_message' => :'progress_message',
        :'operation_type' => :'operation_type',
        :'completion_time_usecs' => :'completion_time_usecs',
        :'error_code' => :'error_code',
        :'percentage_complete' => :'percentage_complete',
        :'api_version' => :'api_version',
        :'parent_task_reference' => :'parent_task_reference'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'status' => :'String',
        :'last_update_time' => :'Time',
        :'error_detail' => :'String',
        :'logical_timestamp' => :'Integer',
        :'requested_status' => :'String',
        :'entity_reference_list' => :'Array<Reference>',
        :'start_time' => :'Time',
        :'creation_time' => :'Time',
        :'uuid' => :'String',
        :'start_time_usecs' => :'Integer',
        :'cluster_reference' => :'ClusterReference',
        :'subtask_reference_list' => :'Array<TaskReference>',
        :'completion_time' => :'Time',
        :'creation_time_usecs' => :'Integer',
        :'progress_message' => :'String',
        :'operation_type' => :'String',
        :'completion_time_usecs' => :'Integer',
        :'error_code' => :'String',
        :'percentage_complete' => :'Integer',
        :'api_version' => :'String',
        :'parent_task_reference' => :'TaskReference'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Nutanix::Task` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Nutanix::Task`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'last_update_time')
        self.last_update_time = attributes[:'last_update_time']
      end

      if attributes.key?(:'error_detail')
        self.error_detail = attributes[:'error_detail']
      end

      if attributes.key?(:'logical_timestamp')
        self.logical_timestamp = attributes[:'logical_timestamp']
      end

      if attributes.key?(:'requested_status')
        self.requested_status = attributes[:'requested_status']
      end

      if attributes.key?(:'entity_reference_list')
        if (value = attributes[:'entity_reference_list']).is_a?(Array)
          self.entity_reference_list = value
        end
      end

      if attributes.key?(:'start_time')
        self.start_time = attributes[:'start_time']
      end

      if attributes.key?(:'creation_time')
        self.creation_time = attributes[:'creation_time']
      end

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      end

      if attributes.key?(:'start_time_usecs')
        self.start_time_usecs = attributes[:'start_time_usecs']
      end

      if attributes.key?(:'cluster_reference')
        self.cluster_reference = attributes[:'cluster_reference']
      end

      if attributes.key?(:'subtask_reference_list')
        if (value = attributes[:'subtask_reference_list']).is_a?(Array)
          self.subtask_reference_list = value
        end
      end

      if attributes.key?(:'completion_time')
        self.completion_time = attributes[:'completion_time']
      end

      if attributes.key?(:'creation_time_usecs')
        self.creation_time_usecs = attributes[:'creation_time_usecs']
      end

      if attributes.key?(:'progress_message')
        self.progress_message = attributes[:'progress_message']
      end

      if attributes.key?(:'operation_type')
        self.operation_type = attributes[:'operation_type']
      end

      if attributes.key?(:'completion_time_usecs')
        self.completion_time_usecs = attributes[:'completion_time_usecs']
      end

      if attributes.key?(:'error_code')
        self.error_code = attributes[:'error_code']
      end

      if attributes.key?(:'percentage_complete')
        self.percentage_complete = attributes[:'percentage_complete']
      end

      if attributes.key?(:'api_version')
        self.api_version = attributes[:'api_version']
      else
        self.api_version = '3.1.0'
      end

      if attributes.key?(:'parent_task_reference')
        self.parent_task_reference = attributes[:'parent_task_reference']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if !@uuid.nil? && @uuid !~ pattern
        invalid_properties.push("invalid value for \"uuid\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@uuid.nil? && @uuid !~ Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid Value to be assigned
    def uuid=(uuid)
      if uuid.nil?
        fail ArgumentError, 'uuid cannot be nil'
      end

      pattern = Regexp.new(/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/)
      if uuid !~ pattern
        fail ArgumentError, "invalid value for \"uuid\", must conform to the pattern #{pattern}."
      end

      @uuid = uuid
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          status == o.status &&
          last_update_time == o.last_update_time &&
          error_detail == o.error_detail &&
          logical_timestamp == o.logical_timestamp &&
          requested_status == o.requested_status &&
          entity_reference_list == o.entity_reference_list &&
          start_time == o.start_time &&
          creation_time == o.creation_time &&
          uuid == o.uuid &&
          start_time_usecs == o.start_time_usecs &&
          cluster_reference == o.cluster_reference &&
          subtask_reference_list == o.subtask_reference_list &&
          completion_time == o.completion_time &&
          creation_time_usecs == o.creation_time_usecs &&
          progress_message == o.progress_message &&
          operation_type == o.operation_type &&
          completion_time_usecs == o.completion_time_usecs &&
          error_code == o.error_code &&
          percentage_complete == o.percentage_complete &&
          api_version == o.api_version &&
          parent_task_reference == o.parent_task_reference
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [status, last_update_time, error_detail, logical_timestamp, requested_status, entity_reference_list, start_time, creation_time, uuid, start_time_usecs, cluster_reference, subtask_reference_list, completion_time, creation_time_usecs, progress_message, operation_type, completion_time_usecs, error_code, percentage_complete, api_version, parent_task_reference].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Nutanix.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
