=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::AccountsApi)
    end
  end

  # unit tests for accounts_list_post
  # List the Account
  # List the Account with associated metadata
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [AccountListIntentResponse]
  describe 'accounts_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_post
  # Create Account
  # Given a spec creates a Account with associated metadata 
  # @param body Request body
  # @param [Hash] opts the optional parameters
  # @return [AccountIntentResponse]
  describe 'accounts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_uuid_delete
  # Delete Account
  # Delete an Account given its UUID
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [AccountIntentResponse]
  describe 'accounts_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_uuid_get
  # Get Account
  # Given a UUID, returns a Account definition
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [AccountIntentResponse]
  describe 'accounts_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_uuid_put
  # Update Account
  # Given a spec and Account UUID, update Account 
  # @param uuid The UUID of the entity.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [AccountIntentResponse]
  describe 'accounts_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_uuid_verify_get
  # Verify account
  # Verify account settings
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'accounts_uuid_verify_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
