=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::AwsVmsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AwsVmsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::AwsVmsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AwsVmsApi' do
    it 'should create an instance of AwsVmsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::AwsVmsApi)
    end
  end

  # unit tests for aws_vms_list_post
  # List AWS VMs.
  # List VMs with associated metadata. Supported filters are: - account_uuid - region - power_state Use the account_uuid filter to get all the VMs on the default region of a particular account. Use account_uuid and region filters together to list all the VMs in a particular region. Set the power_state to running, stopped, and terminated. in the above two cases to list only VMs in the particular power state. 
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [AwsVmListIntentResponse]
  describe 'aws_vms_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aws_vms_post
  # Create an AWS instance(VM)
  # A VM is a logical representation of a computer (CPU, memory, storage, and operating system) 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [AwsVmIntentResponse]
  describe 'aws_vms_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aws_vms_uuid_delete
  # Delete an AWS VM.
  # Delete an AWS VM given its uuid.
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [AwsVmIntentResponse]
  describe 'aws_vms_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aws_vms_uuid_get
  # Get an AWS VM.
  # Given a UUID, returns an AWS VM definition.
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [AwsVmIntentResponse]
  describe 'aws_vms_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for aws_vms_uuid_put
  # Update an AWS VM.
  # Given an intenful spec and VM uuid, update an AWS VM.
  # @param uuid The UUID of the entity.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [AwsVmIntentResponse]
  describe 'aws_vms_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
