=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::AwsKeyPairsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AwsKeyPairsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::AwsKeyPairsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AwsKeyPairsApi' do
    it 'should create an instance of AwsKeyPairsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::AwsKeyPairsApi)
    end
  end

  # unit tests for aws_key_pairs_list_post
  # List all the AWS key pairs
  # List all the AWS key pairs. Supported filters are: - account_uuid - region Use account_uuid filter to list all the key pairs on the default region of a particular AWS account. Use account_uuid and region filters together to list the key pairs on a particular region of an AWS account. 
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [AwsKeyPairListIntentResponse]
  describe 'aws_key_pairs_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
