=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::AwsRolesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AwsRolesApi' do
  before do
    # run before each test
    @api_instance = Nutanix::AwsRolesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AwsRolesApi' do
    it 'should create an instance of AwsRolesApi' do
      expect(@api_instance).to be_instance_of(Nutanix::AwsRolesApi)
    end
  end

  # unit tests for aws_roles_list_post
  # List all the AWS roles
  # List all the AWS roles. Supported filters are: - account_uuid - region Use account_uuid filter to list all the roles on the default region of a particular AWS account. Use account_uuid and region filter together to list all the roles on a particular region of an aws_account. 
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [AwsRoleListIntentResponse]
  describe 'aws_roles_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
