=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::BlackoutsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlackoutsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::BlackoutsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlackoutsApi' do
    it 'should create an instance of BlackoutsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::BlackoutsApi)
    end
  end

  # unit tests for blackouts_list_post
  # Retrieve all blackout objects
  # Retrieve all blackout objects
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [BlackoutListIntentResponse]
  describe 'blackouts_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blackouts_post
  # Create blackout object
  # Create a blackout object
  # @param body Create blackout object
  # @param [Hash] opts the optional parameters
  # @return [BlackoutIntentResponse]
  describe 'blackouts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blackouts_uuid_delete
  # Delete specified blackout object
  # Delete specified blackout object
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [BlackoutIntentResponse]
  describe 'blackouts_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blackouts_uuid_get
  # Retrieve specified blackout object
  # Retrieve specified blackout object
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [BlackoutIntentResponse]
  describe 'blackouts_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blackouts_uuid_put
  # Update blackout entity
  # Update blackout entity
  # @param uuid The UUID of the entity.
  # @param body Update blackout
  # @param [Hash] opts the optional parameters
  # @return [BlackoutIntentResponse]
  describe 'blackouts_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
