=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::BlueprintApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlueprintApi' do
  before do
    # run before each test
    @api_instance = Nutanix::BlueprintApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlueprintApi' do
    it 'should create an instance of BlueprintApi' do
      expect(@api_instance).to be_instance_of(Nutanix::BlueprintApi)
    end
  end

  # unit tests for blueprints_brownfield_import_vms_list_post
  # List the vms available for import
  # List the blueprint launch pending request with the filters - platform_type - account_uuid - platform_filters
  # @param body Request body
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'blueprints_brownfield_import_vms_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_import_file_post
  # Create Blueprint from file
  # Creates a blueprint from uploaded file
  # @param body blueprint_file
  # @param [Hash] opts the optional parameters
  # @return [BlueprintUploadOutput]
  describe 'blueprints_import_file_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_import_json_post
  # Create Blueprint using json
  # Given a spec creates a Blueprint with associated metadata 
  # @param body Request body
  # @param [Hash] opts the optional parameters
  # @return [BlueprintUploadOutput]
  describe 'blueprints_import_json_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_list_post
  # List the Blueprint
  # List the Blueprint with associated metadata
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [BlueprintListIntentResponse]
  describe 'blueprints_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_marketplace_launch_post
  # Launch the marketplace item
  # Launch the given marketplace item 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [BlueprintMarketplaceLaunchResponse]
  describe 'blueprints_marketplace_launch_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_pending_launches_list_post
  # List the pending Blueprint launches
  # List the blueprint launch pending requests
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [BlueprintPendingLaunchesListResponse]
  describe 'blueprints_pending_launches_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_post
  # Create Blueprint
  # Given a spec creates a Blueprint with associated metadata 
  # @param body Request body
  # @param [Hash] opts the optional parameters
  # @return [BlueprintIntentResponse]
  describe 'blueprints_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_clone_post
  # Clone the blueprint
  # Clone the given blueprint 
  # @param uuid Uuid of blueprint to be cloned
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [BlueprintCloneResponse]
  describe 'blueprints_uuid_clone_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_delete
  # Delete Blueprint
  # Delete a Blueprint given its UUID
  # @param uuid uuid of the blueprint to be deleted
  # @param [Hash] opts the optional parameters
  # @return [BlueprintIntentResponse]
  describe 'blueprints_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_export_file_get
  # Download blueprint file
  # Given a UUID, returns a Blueprint file
  # @param uuid uuid of Blueprint to get
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'blueprints_uuid_export_file_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_export_json_get
  # Get Blueprint in json format
  # Given a UUID, returns a Blueprint definition
  # @param uuid uuid of Blueprint to get
  # @param [Hash] opts the optional parameters
  # @return [BlueprintDownloadIntentResponse]
  describe 'blueprints_uuid_export_json_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_get
  # Get Blueprint
  # Given a UUID, returns a Blueprint definition
  # @param uuid uuid of Blueprint to get
  # @param [Hash] opts the optional parameters
  # @return [BlueprintIntentResponse]
  describe 'blueprints_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_launch_post
  # Launch the blueprint
  # Launch the given blueprint 
  # @param uuid Uuid of blueprint to be launched
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [BlueprintLaunchResponse]
  describe 'blueprints_uuid_launch_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_pending_launches_launched_uuid_get
  # Get the pending launch details
  # Get the details of the pending launch with the given uuid
  # @param uuid uuid of Blueprint to get
  # @param launched_uuid Launched uuid of blueprint
  # @param [Hash] opts the optional parameters
  # @return [BlueprintPendingLaunchesResource]
  describe 'blueprints_uuid_pending_launches_launched_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for blueprints_uuid_put
  # Update Blueprint
  # Given a spec and Blueprint UUID, update Blueprint 
  # @param uuid uuid of blueprint to be updated
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [BlueprintIntentResponse]
  describe 'blueprints_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
