=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::EntitySyncRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EntitySyncRulesApi' do
  before do
    # run before each test
    @api_instance = Nutanix::EntitySyncRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EntitySyncRulesApi' do
    it 'should create an instance of EntitySyncRulesApi' do
      expect(@api_instance).to be_instance_of(Nutanix::EntitySyncRulesApi)
    end
  end

  # unit tests for entity_sync_rules_list_post
  # Get a list of existing entity_sync_rules
  # This operation gets a list of entity_sync_rules, allowing for sorting and pagination. Note: Entities that have not been created successfully are not listed. 
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [EntitySyncRuleListIntentResponse]
  describe 'entity_sync_rules_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entity_sync_rules_post
  # Create a new entity_sync_rule
  # This operation submits a request to create a new entity_sync_rule based on the input parameters. 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [EntitySyncRuleIntentResponse]
  describe 'entity_sync_rules_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entity_sync_rules_uuid_delete
  # Delete a existing entity_sync_rule
  # This operation submits a request to delete a existing entity_sync_rule.
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'entity_sync_rules_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entity_sync_rules_uuid_get
  # Get a existing entity_sync_rule
  # This operation gets a existing entity_sync_rule.
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [EntitySyncRuleIntentResponse]
  describe 'entity_sync_rules_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entity_sync_rules_uuid_list_entities_to_sync_get
  # Get the list of entities which needs to be synced. 
  # Get the list of entities that are affected by this entity sync rule which needs to be synced to connected Availability Zones. 
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_categories Boolean to indicate whether the categories should be included in the response or not. 
  # @option opts [String] :sort_attribute The attribute to perform sort on.
  # @option opts [String] :sort_order The sort order in which results are to be returned.
  # @option opts [Integer] :offset Offset from start of the entity list.
  # @option opts [Integer] :length The number of records to retrieve relative to the offset.
  # @return [Array<ListEntitiesToSyncResponseInner>]
  describe 'entity_sync_rules_uuid_list_entities_to_sync_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entity_sync_rules_uuid_process_post
  # Process an entity sync rule.
  # It will be used whenever user wants to process an entity sync rule immediately, irrespective of sync trigger or schedule. It will override entities in case of conflicts. 
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<EntitySyncRuleProcessInputInner>] :body 
  # @return [ProceduralResponse]
  describe 'entity_sync_rules_uuid_process_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for entity_sync_rules_uuid_put
  # Update a existing entity_sync_rule
  # This operation submits a request to update a existing entity_sync_rule based on the input parameters. 
  # @param uuid The UUID of the entity.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [EntitySyncRuleIntentResponse]
  describe 'entity_sync_rules_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
