=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::PhysicalAvailabilityZoneApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PhysicalAvailabilityZoneApi' do
  before do
    # run before each test
    @api_instance = Nutanix::PhysicalAvailabilityZoneApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PhysicalAvailabilityZoneApi' do
    it 'should create an instance of PhysicalAvailabilityZoneApi' do
      expect(@api_instance).to be_instance_of(Nutanix::PhysicalAvailabilityZoneApi)
    end
  end

  # unit tests for tenant_clusters_physical_availability_zone_get
  # Physical Availability zone configuration.
  # Physical Availability zone configuration.
  # @param [Hash] opts the optional parameters
  # @return [PhysicalAvailabilityZone]
  describe 'tenant_clusters_physical_availability_zone_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tenant_clusters_physical_availability_zone_keys_get
  # Get Physical Availability Zone&#39;s JWKS
  # JSON Web Key Set (JWKS) that contains public keys. The keys can be used to verify the signatures of tokens issued by the PC, My.Nutanix (IDP), IAM and Okta. 
  # @param [Hash] opts the optional parameters
  # @return [KeySetResponse]
  describe 'tenant_clusters_physical_availability_zone_keys_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tenant_clusters_physical_availability_zone_post
  # Configure a Physical Availability zone.
  # Configure a Physical Availability zone.
  # @param physical_availability_zone Physical Availability Zone Configuration details.
  # @param [Hash] opts the optional parameters
  # @return [PhysicalAvailabilityZoneStatus]
  describe 'tenant_clusters_physical_availability_zone_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
