=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::RecoveryPlansApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecoveryPlansApi' do
  before do
    # run before each test
    @api_instance = Nutanix::RecoveryPlansApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecoveryPlansApi' do
    it 'should create an instance of RecoveryPlansApi' do
      expect(@api_instance).to be_instance_of(Nutanix::RecoveryPlansApi)
    end
  end

  # unit tests for recovery_plans_list_post
  # List the Recovery Plans
  # List the Recovery Plans with associated metadata
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [RecoveryPlanListIntentResponse]
  describe 'recovery_plans_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recovery_plans_post
  # Create Recovery Plan
  # Given a spec creates a Recovery Plan with associated metadata 
  # @param body Request body
  # @param [Hash] opts the optional parameters
  # @return [RecoveryPlanIntentResponse]
  describe 'recovery_plans_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recovery_plans_uuid_delete
  # Delete Recovery Plan
  # Delete a Recovery Plan given its UUID
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [RecoveryPlanIntentResponse]
  describe 'recovery_plans_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recovery_plans_uuid_entities_get
  # Get entities associated with the Recovery Plan
  # Entities associated with the Recovery Plan. It includes the live entities and the entities for which Recovery Points are present on the local Availability Zones/Public Cloud. 
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :action_type The entities that will be recovered when an operation is performed on the Recovery Plan. Below is the list of supported action types. MIGRATE - Entities will be recovered from their latest state in the   Recovery Availability Zone. LIVE_MIGRATE - Entities will be recovered from their latest state   in the Recovery Availability Zone without VM down time. FAILOVER - Entities will be recovered from a Recovery Point at   Recovery Availability Zone. TEST_FAILOVER - Entities will be recovered from the latest Recovery   Point in the test network. 
  # @option opts [Array<String>] :failed_availability_zone_info_list List of Availability Zone URL and cluster UUIDs. Sample format is \&quot;&lt;az_url&gt;|&lt;cluster_uuid_1&gt;|&lt;cluster_uuid_2&gt;|...\&quot; where cluster_uuids are optional. 
  # @option opts [Array<String>] :recovery_availability_zone_info_list List of Availability Zone URL and cluster UUIDs. Sample format is \&quot;&lt;az_url&gt;|&lt;cluster_uuid_1&gt;|&lt;cluster_uuid_2&gt;|...\&quot; where cluster_uuids are optional. 
  # @option opts [Time] :recovery_reference_time Time with respect to which entities has to be fetched for Unplanned Failover. This time will be used as reference time with respect to which latest snapshot will have to be restored in case of failover. For example, if failover is required to be done using snapshot created on or before yesterday &#39;2:00&#39; PM, then recovery_reference_time will be set to this time. This would be given in the format %Y-%m-%dT%H:%M:%SZ. 
  # @return [RecoveryPlanEntities]
  describe 'recovery_plans_uuid_entities_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recovery_plans_uuid_get
  # Get Recovery Plan
  # Given a UUID, returns a Recovery Plan definition
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [RecoveryPlanIntentResponse]
  describe 'recovery_plans_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recovery_plans_uuid_put
  # Update Recovery Plan
  # Given a spec and Recovery Plan UUID, update Recovery Plan 
  # @param uuid The UUID of the entity.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [RecoveryPlanIntentResponse]
  describe 'recovery_plans_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
