=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::RecoveryPointsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RecoveryPointsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::RecoveryPointsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecoveryPointsApi' do
    it 'should create an instance of RecoveryPointsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::RecoveryPointsApi)
    end
  end

  # unit tests for recovery_points_uuid_replicate_post
  # Replicate a Recovery Point
  # Submits a request to replicate a Recovery Point from source Availability Zone to target Availability Zone. The successful request returns a task ID to track the replication status. 
  # @param uuid The UUID of the entity.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ProceduralResponse]
  describe 'recovery_points_uuid_replicate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for recovery_points_uuid_restore_post
  # Restore a recovery point.
  # Submits a request to create a task handling the restore of a recovery point, returns the task reference. This operation is used to restore an entire composite recovery point or a subset of entities from it. Follow the task to get the reference of the created entities. 
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @option opts [RecoveryPointRestoreInput] :body 
  # @return [ProceduralResponse]
  describe 'recovery_points_uuid_restore_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
