=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::StreamingPolicyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StreamingPolicyApi' do
  before do
    # run before each test
    @api_instance = Nutanix::StreamingPolicyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StreamingPolicyApi' do
    it 'should create an instance of StreamingPolicyApi' do
      expect(@api_instance).to be_instance_of(Nutanix::StreamingPolicyApi)
    end
  end

  # unit tests for streaming_policies_list_post
  # Retrieves all Streaming Policies
  # Retrieves all Streaming Policies
  # @param get_entities_request 
  # @param [Hash] opts the optional parameters
  # @return [StreamingPolicyListIntentResponse]
  describe 'streaming_policies_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for streaming_policies_post
  # Create Streaming Policy
  # Create Streaming Policy
  # @param body Create Streaming Policy object
  # @param [Hash] opts the optional parameters
  # @return [StreamingPolicyIntentResponse]
  describe 'streaming_policies_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for streaming_policies_uuid_delete
  # Delete specified Streaming Policy
  # Delete specified Streaming Policy
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [StreamingPolicyIntentResponse]
  describe 'streaming_policies_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for streaming_policies_uuid_get
  # Retrieves specified Streaming Policy
  # Retrieves specified Streaming Policy
  # @param uuid The UUID of the entity.
  # @param [Hash] opts the optional parameters
  # @return [StreamingPolicyIntentResponse]
  describe 'streaming_policies_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for streaming_policies_uuid_put
  # Update Streaming Policy entity
  # Update Streaming Policy entity
  # @param uuid The UUID of the entity.
  # @param body Update Streaming Policy
  # @param [Hash] opts the optional parameters
  # @return [StreamingPolicyIntentResponse]
  describe 'streaming_policies_uuid_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
