=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::TenantsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TenantsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::TenantsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TenantsApi' do
    it 'should create an instance of TenantsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::TenantsApi)
    end
  end

  # unit tests for tenant_clusters_account_terminate_post
  # Terminate a tenant account
  # Terminate a tenant account by stopping the tenant user vms in the cloud and unpairing from the trusted onprem cloud. This request is supported only on XI Prism Central. 
  # @param [Hash] opts the optional parameters
  # @return [ProceduralResponse]
  describe 'tenant_clusters_account_terminate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for tenant_clusters_config_tenants_post
  # Create a new Tenant
  # This operation submits a request to create a new Tenant based on the input parameters. 
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [TenantStatus]
  describe 'tenant_clusters_config_tenants_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
