=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Nutanix::VersionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VersionsApi' do
  before do
    # run before each test
    @api_instance = Nutanix::VersionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VersionsApi' do
    it 'should create an instance of VersionsApi' do
      expect(@api_instance).to be_instance_of(Nutanix::VersionsApi)
    end
  end

  # unit tests for versions_get
  # Get details on the api version
  # A version is the major and minor number of the API.
  # @param [Hash] opts the optional parameters
  # @return [Versions]
  describe 'versions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
