=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Nutanix::FlowService
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Nutanix::FlowService do
  let(:instance) { Nutanix::FlowService.new }

  describe 'test an instance of FlowService' do
    it 'should create an instance of FlowService' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Nutanix::FlowService)
    end
  end

  describe 'test attribute "tcp_port_range_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "protocol"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "udp_port_range_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "icmp_type_code_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
