=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Nutanix::InternalRoutingProtocolConfigStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Nutanix::InternalRoutingProtocolConfigStatus do
  let(:instance) { Nutanix::InternalRoutingProtocolConfigStatus.new }

  describe 'test an instance of InternalRoutingProtocolConfigStatus' do
    it 'should create an instance of InternalRoutingProtocolConfigStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Nutanix::InternalRoutingProtocolConfigStatus)
    end
  end

  describe 'test attribute "local_prefix_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ibgp_config_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "ospf_config"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
