=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Nutanix::RecoveryPointResourceReservationSpecResourceReservationSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Nutanix::RecoveryPointResourceReservationSpecResourceReservationSpec do
  let(:instance) { Nutanix::RecoveryPointResourceReservationSpecResourceReservationSpec.new }

  describe 'test an instance of RecoveryPointResourceReservationSpecResourceReservationSpec' do
    it 'should create an instance of RecoveryPointResourceReservationSpecResourceReservationSpec' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Nutanix::RecoveryPointResourceReservationSpecResourceReservationSpec)
    end
  end

  describe 'test attribute "operation_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reservation_lease_timeout_secs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
