=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Nutanix::SecurityPlanningClusterCapability
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Nutanix::SecurityPlanningClusterCapability do
  let(:instance) { Nutanix::SecurityPlanningClusterCapability.new }

  describe 'test an instance of SecurityPlanningClusterCapability' do
    it 'should create an instance of SecurityPlanningClusterCapability' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Nutanix::SecurityPlanningClusterCapability)
    end
  end

  describe 'test attribute "cluster_uuid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cluster_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data_collector_prechecks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "traffic_visibility_prechecks"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
