=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Nutanix::StoragePolicyComplianceCount
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Nutanix::StoragePolicyComplianceCount do
  let(:instance) { Nutanix::StoragePolicyComplianceCount.new }

  describe 'test an instance of StoragePolicyComplianceCount' do
    it 'should create an instance of StoragePolicyComplianceCount' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Nutanix::StoragePolicyComplianceCount)
    end
  end

  describe 'test attribute "total_entities"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "num_non_compliance_entities"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "num_compliant_entities"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
