=begin
#Nutanix Intentful API

#Move programming from the user to the machine.

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Nutanix::VmRecoveryPointsCloneInput
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Nutanix::VmRecoveryPointsCloneInput do
  let(:instance) { Nutanix::VmRecoveryPointsCloneInput.new }

  describe 'test an instance of VmRecoveryPointsCloneInput' do
    it 'should create an instance of VmRecoveryPointsCloneInput' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Nutanix::VmRecoveryPointsCloneInput)
    end
  end

  describe 'test attribute "override_spec"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "vm_recovery_point_uuid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cluster_reference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "availability_zone_reference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
